# Generated by Django 4.2.7 on 2023-11-06 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_wrongauthor_wrongtag_wrongquote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrongquote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='wrongquote',
            name='tags',
        ),
        migrations.DeleteModel(
            name='WrongAuthor',
        ),
        migrations.DeleteModel(
            name='WrongQuote',
        ),
        migrations.DeleteModel(
            name='WrongTag',
        ),
    ]
