# Generated by Django 4.2.7 on 2023-11-06 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_remove_wrongquote_author_remove_wrongquote_tags_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='WrongAuthor',
        ),
        migrations.RenameModel(
            old_name='Quote',
            new_name='WrongQuote',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='WrongTag',
        ),
    ]
