# Generated by Django 4.2.7 on 2023-11-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_rename_author_wrongauthor_rename_quote_wrongquote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrongquote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='wrongquote',
            name='tags',
        ),
        migrations.DeleteModel(
            name='WrongAuthor',
        ),
        migrations.DeleteModel(
            name='WrongQuote',
        ),
        migrations.DeleteModel(
            name='WrongTag',
        ),
    ]
